site_name: Outorga-Antecipada
site_url: https://sitename.example

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Projeto Multidisciplinar:
    - Detalhamento do Problema: detalhamento_problema.md
    - Requisitos: projeto/requisitos.md
    - Arquitetura: projeto/arquitetura.md
    - Sugestões de Melhoria: projeto/melhorias.md
  - Evolução do Material de Apoio à Disciplina:
    - Detalhamento: projeto/detalhamento.md
  - Planejamento e Monitoramento: 
    - Roadmap atualizado: planejamento/roadmap.md
    - Quadro de Atividades e distribuição de tarefas: planejamento/tarefas.md
  - Relatório de Atividades:
    - Milestone 1: entregas/pc1.md
    - Milestone 2: entregas/pc2.md
    - Milestone 3: entregas/pc3.md
