site_name: Outorga-Antecipada
site_url: https://sitename.example

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Projeto Multidisciplinar:
    - Detalhamento do Problema: projeto/detalhamento.md
    - Requisitos: projeto/requisitos.md
    - Arquitetura: projeto/arquitetura.md
    - Sugestões de Melhoria: projeto/melhorias.md
  - Evolução do Material de Apoio à Disciplina:
    - Github: disciplina/github.md
    - SonarCube: disciplina/sonar.md
  - Planejamento e Monitorrmento: 
    - Roadmap atualizado (ZenHub): planejamento/roadmap.md
    - Quadro de Atividades e distribuição de tarefas: planejamento/tarefas.md
  
