site_name: Outorga-Antecipada
site_url: https://sitename.example

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Arquitetura - Esteira Inteligente: arquitetura.md
